### ISSUE TITLE
Error message with 4.6

### ISSUE THREAD

**Issue by gabrielt** [Lavoaster/IP.Board-Steam-Authentication-Method#125]
Getting the following error when trying to link an IPS account to a Steam account:

`Error: Call to undefined method IPS\Http\Url\Friendly::getFurlQuery() (0)
#0 [redacted]/system/Login/Login.php(339): IPS\steam\Login\_Steam->authenticateButton()
#1 [redacted]/applications/core/modules/front/system/settings.php(1462): IPS\_Login->authenticate()
#2 [redacted]/applications/core/modules/front/system/settings.php(57): IPS\core\modules\front\system\_settings->_login()
#3 [redacted]/system/Dispatcher/Controller.php(101): IPS\core\modules\front\system\_settings->manage()
#4 [redacted]/applications/core/modules/front/system/settings.php(42): IPS\Dispatcher\_Controller->execute()
#5 [redacted]/system/Dispatcher/Dispatcher.php(153): IPS\core\modules\front\system\_settings->execute()
#6 [redacted]/index.php(13): IPS\_Dispatcher->run()
#7 {main}`

**Comment by Davinel17** [comment]
same error
