### ISSUE TITLE
ProfileSyncAbstract Not Found

### ISSUE THREAD

**Issue by Maihym** [Lavoaster/IP.Board-Steam-Authentication-Method#94]
I've uploaded all the the files from the upload folder and changed the applications permissions to 770 and the system permissions to 750. I try to go to members and I get this error 

> 
Error: Class 'IPS\core\ProfileSync\ProfileSyncAbstract' not found (0)
#0 /home/maihym/www-data/www.chaoticgaming.org/system/Theme/Theme.php(824) : eval()'d code(1592): IPS\_Member->connectedProfileSyncServices()
#1 /home/maihym/www-data/www.chaoticgaming.org/system/Theme/SandboxedTemplate.php(56): IPS\Theme\class_core_admin_members->editMemberHeader(Object(IPS\Member), true)
#2 /home/maihym/www-data/www.chaoticgaming.org/applications/core/modules/admin/members/members.php(1002): IPS\Theme\_SandboxedTemplate->__call('editMemberHeade...', Array)
#3 /home/maihym/www-data/www.chaoticgaming.org/system/Dispatcher/Controller.php(85): IPS\core\modules\admin\members\_members->edit()
#4 /home/maihym/www-data/www.chaoticgaming.org/system/Dispatcher/Dispatcher.php(146): IPS\Dispatcher\_Controller->execute()
#5 /home/maihym/www-data/www.chaoticgaming.org/admin/index.php(13): IPS\_Dispatcher->run()
#6 {main}

**Comment by Maihym** [comment]
I found out I deleted some files that weren't supposed to be deleted
